### ISSUE TITLE
EnderZoo compatibility with JourneyMap's Icons

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderZoo#157]
When using JourneyMap's option to show mob icons instead of just cursors EnderZoo's entities will not show up properly, see for yourself:

![2016-11-27_15 20 02](https://cloud.githubusercontent.com/assets/8670392/20649197/aa59fa5a-b4b9-11e6-9d33-acec38f58e00.png)

Is there anything that can be done to improve compatibility with JourneyMap? I like using the icons and EnderZoo makes it hard to see what's where.

**Comment by AnrDaemon** [comment]
Wiich MC version? 1.7 or 1.10 ?

**Comment by HenryLoenwind** [comment]
I already did those icons a while back...um, where are they? Give me a moment...

**Comment by Xiaminou** [comment]
@AnrDaemon It's 1.10.2

**Comment by HiddenCobalt** [comment]
So where exactly am I suppose to put the icons? The JM documentation is not very clear; I see two folders mentioned in the _**[article](http://journeymap.info/Custom_Mob_Icon_Sets)**_ about making custom mob icons; "entity_icon" and "entity_icons" and I'm not quite sure which one it is. I'm **guessing** this problem is probably on the map overlay coding side of things but the **_[JM issues hub](https://bitbucket.org/TeamJM/journeymap/issues/131/recent-versions-negatively-effect-custom)_** doesn't seem to be exactly jumping at the problem. In any case I thought maybe @HenryLoenwind you would know since you took the time to add the icons.
