### ISSUE TITLE
  Khndrel Keght Spawning despite proper tool?

### ISSUE THREAD

**Issue by Vercalos** [SleepyTrousers/EnderZoo#217]
Playing on Minecraft 1.12.2 with Ender IO Zoo 1.51. Some mod-added shovels trigger the mob spawning. I've caused Khndrel Keght spawns with the following:
Project E - both dark and red matter shovels
Tinkers' Construct - Mattock(combination Axe/Shovel) causes spawning, but shovels don't

**Comment by HenryLoenwind** [comment]
A shovel isn't a shovel because it has "shovel" in its name. It's a shovel when it can break blocks that require a shovel in a way that they drop their item. There are no blocks in vanilla that require shovels (unlike pickaxe, there are many blocks that require a pickaxe to drop an item), so many mods just don't care.
