### ISSUE TITLE
Bug with potions

### ISSUE THREAD

**Issue by Sunconure11** [SleepyTrousers/EnderZoo#48]
It appears your wither potions conflict in some weird way with potions of leaping from other mods, creating a weird potion that inflicts both wither and leaping.

**Comment by tterrag1098** [comment]
What "other mods"? This should not be possible unless they are doing something really wrong.

**Comment by Sunconure11** [comment]
Erebus and Ars Magica 2 mainly.

**Comment by tterrag1098** [comment]
I need versions and a screenshot. This is very odd.

**Comment by Sunconure11** [comment]
I think it happened with 1.0.6.15 - 16. I have not tried the latest version yet because of this bug.

**Comment by Sunconure11** [comment]
I decided to test out the latest version of this mod, and it is still happening.

**Comment by banjomarx** [comment]
um i think this is still happening when i get hit by a witherwitch potion in my mudpack it crashes to desktop (1.7.10) and i am using the newest 1.7.10 vers too so ya. here is the crash report
http://pastebin.com/DhSDds6y
as you can see we have quite the mudpack. I was having this problem before dragonapi was added so its not that (ik it messes with making more potion ids and stuff)

**Comment by banjomarx** [comment]
also i checked my configs and i do not see the options in mine please help

**Comment by banjomarx** [comment]
ya i have confirmed it seems to be a problem where the potion of decay has a drowning potion effect on it as well as the wither

**Comment by banjomarx** [comment]
ok i found its an issue with the drowning potion effect in blood magic, which can be configured there. srry

**Comment by banjomarx** [comment]
but changing that just causes other potion effects to take over... meaning now it overrides with other potion effects like reflect dmg.... please fix

**Comment by tterrag1098** [comment]
It's ***ALWAYS*** an ID issue. Fix your configs.

**Comment by banjomarx** [comment]
well i am UNABLE TO FIX THE CONFIGS!!!!! i dont want to point fingers here and i am VERY SORRY (not sarcasm im just really frustrated today) if i come accross as rude but while it seems like your mod was updated for 1.8, it has NOT been updated with the config fix that it looks like u applied 7 days ago. the most recent update to a 1.7.10 compatible version appears to be from Jan 2 which means it does not have the fix i need. as i am sure you know most other mods use a system to automatically place their potion effects so that they will not conflict. mods that use this do not always allow me to fix them via config, and it seems like they are all targeting your spot for some reason, causing alot of trouble since i cannot edit your id configs! I apologize if i am coming across as rude but this is hands down my FAVORITE mob mod and i feel really frustrated that i cant get it working, i dont want to have to remove it cuz i love messing around with wither witches and stuff

**Comment by tterrag1098** [comment]
Sorry about that, I was unaware the fix was unreleased. Should be a new build on curseforge shortly.

**Comment by banjomarx** [comment]
ok thank you i will grab it asap!

**Comment by banjomarx** [comment]
i hate to be annoying but the new update still doesnt have that  config option, and yes i did delete the entire old config folder first
