### ISSUE TITLE
Information for Mob Khndrel Keght?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderZoo#99]
I can't seem to find any info for the new mob Khndrel Keght....it's a strange one...

**Comment by Tsunayoshi** [comment]
"dire slime" {
    # Base attack damage of the dire slime.
    D:direSlimeAttackDamage=3.0

    # Base attack damage of the large dire slime.
    D:direSlimeAttackDamageLarge=8.0

    # Base attack damage of the medium dire slime.
    D:direSlimeAttackDamageMedium=5.0

    # The chance that a Dire Slime will be spawned (0 = never, 1 = always).
    D:direSlimeChance=0.65

    # The chance a large will spawn when a medium Dire Slimes is killed (eg 0.02 for a 2% chance)
    D:direSlimeChanceLarge=0.2

    # The chance a medium will spawn when a small Dire Slimes is killed (eg 0.12 for a 12% chance).
    D:direSlimeChanceMedium=0.4

    # If false Dire Slime will be disabled [default: true]
    B:direSlimeEnabled=true

    # Base health of the Dire Slime. 
    D:direSlimeHealth=4.0

    # Base health of the medium Dire Slime. 
    D:direSlimeHealthLarge=20.0

    # Base health of the medium Dire Slime. 
    D:direSlimeHealthMedium=8.0
}

**Comment by tekman123** [comment]
there are no config options for this mob at all and I would like to disable them entirely because when they spawn they do not show and I can't do /cofh killall khndrel keght to kill them

**Comment by CrazyPants** [comment]
There are config options, look for dire slime, that's what they are called
internally.

They only spawn when breaking dirt without a shovel. The chance per block
is the chance for the smallest one. When one is killed there is a chance it
will spawn a larger one.

there are no config options for this mob at all and I would like to disable
them entirely because when they spawn they do not show and I can't do /cofh
killall khndrel keght to kill them

—
Reply to this email directly or view it on GitHub
<https://github.com/SleepyTrousers/EnderZoo/issues/99#issuecomment-130087613>
.

**Comment by tterrag1098** [comment]
I updated @CrazyPants for clarity...seems his email was improperly formatted or something...idk.

**Comment by HenryLoenwind** [comment]
Here's a bit of backstory:

Be aware, o wanderer, that many things in the world of Minecraftia are alive. Even the world itself is. And just like other living beings, Minecraftia can feel pain. So be gentle and always use the right tool for the job. Otherwise her pain may result in anger, and her anger may give life to a Khndrel Keght.

If your carelessness has given life to a Khndrel Keght, you need to be prepared. Every hit, be it with hand or sword, will increase its rage...

**Comment by bence98** [comment]
I found a (kind of a) bug: they spawn even when you're using the Vajra from GraviSuite, though that's supposed to be a pick, shovel and axe in one tool.

**Comment by HenryLoenwind** [comment]
Then report it to GraviSuite. Their tool needs to implement this:

    @Override
    public Set<String> getToolClasses(ItemStack stack) {
      Set<String> set = Sets.newHashSet("pickaxe");
      if(whatever) {
        set.add("shovel");
      }
      if(whatever) {
        set.add("axe");
      }
      return set;
    }

**Comment by jlbrewer** [comment]
I'm not sure if this is Tinker's Construct's issue or Ender Zoo's but the Tinker's contruct Mattock is an issue. It's description is that it specifically is able to dig dirt and cut wood, though a bit slower than either a shovel or an axe, while also being a replacement for a hoe. It is not really a shovel since it can't handle any other block a shovel does (sand, gravel, etc), but it ought to count for the purposes of the Khndrel Keght.
